name: xafsflow-env
channels:
  - conda-forge
  - wpk-nist
dependencies:
  - python=3.8
  # because using scm versioning
  - setuptools>=38.4
  # cli
  - matplotlib
  - seaborn
  - numpy
  - scipy
  - pandas
  - xarray
  - bottleneck
  - scikit-learn
  # - lmfit
  - cmomy
  - tqdm
  # Additional?
  # # - cmomy
  # - pip
  # - pip:
  #     - tensorflow
  #     # - tensorflow-probability
